
    select 
        PO_NUMBER               as "Order Number",
        PO_ITEM                 as "Order Item",
        DOC_TYPE                as "Document Type",
        PO_STATUS               as "PO Status",
        DELETION_IND_ITM        as "Deletion Indicator",
        MATERIAL_NUMBER         as "Material Number",
        VENDOR_NUMBER           as "Vendor Number",
        VENDOR_NAME             as "Vendor Name",
        SUPPLIER_NUMBER         as "Supplier Number",
        SUPPLIER_NAME           as "Supplier Name",
        CUSTOMER_NUMBER         as "Customer Number",
        CUSTOMER_NAME           as "Customer Name",
        ITEM_CATEGORY           as "Item Category",
        PLANT                   as "Plant",
        DOCUMENT_DATE           as "Document Date",
        ORDERING_REASON         as "Ordering Reason",
        COMPANY_CODE            as "Company Code",
        STORAGE_LOCATION        as "Storage Location",
        CREATE_DATE             as "PO Creation Date",
        CHANGED_TIMESTAMP       as "PO Changed Timestamp",
        INCOTERM1               as "Incoter1",
        INCOTERM2               as "Incoterm2",
        PAYMENT_TERM            as "Payment Term",
        SHIPPING_CONDITION      as "Shipping Condition",
        CRM_REF_NUMBER          as "CRM Ref. Number",
        PERSON_CREATED          as "Person Created PO",
        PROC_STATE              as "Proc. State",
        INFO_RECORD             as "Info Record",
        REJECTION_IND           as "Rejection Indicator",
        FINAL_INVOICE_IND       as "Final Invoice Indicator",
        INVOICE_RECEIPT_IND     as "Invoice Receipt Indicator",
        SHIPPING_INSTRUCTION    as "Shipping Instruction",
        HIGHER_LEVITEM          as "Higher Level Indicator",
        BASE_UNIT_MEASURE       as "Base Unit of Measure",
        CURRENCY                as "Currency",
        NET_ORDER_VALUE         as "Net Order Value",
        ORDERING_REASON         as "Order Quantity",
        LOAD_DATETIME           as "Load/Update Date" 
        from SPARC_BASE.TRANSACTIONAL.PURCHASE_ORDER_ITEM
        where HIGHER_LEVITEM not in ('00000')
   ) ;