
version: 2

models:
    - name: Purchase_Order_Item
      description: "Purchase Order Item Model"
 #     config: 
 #         materialized: 'incremental'
 #         unique_key:'Order'

    - name: Purchase_OrderItem
      description: "Purchase Order Item Model: Monitoring Report"
 #     config: 
 #         materialized: 'incremental'
 #         unique_key:'Order'
      columns: 
          - name: Order
            description: "The primary key for this table"
           # tests:
           #     - unique
           #     - not_null


