
version: 2

models:
    - name: FACT_PURCHASE_ORDERITEM
      description: "Purchase Order Item Base"

    - name: Purchase_Order_Item
      description: "Purchase Order Item Model"
 #     config: 
 #         materialized: 'incremental'
 #         unique_key:'Order'

    - name: my_first_dbt_model
      description: "First DBT model"
#       config: 
#          materialized: 'view'
#         unique_key:'Order'
#      columns: 
#          - name: Order
#            description: "The primary key for this table"
           # tests:
           #     - unique
           #     - not_null

    - name: purchaseOrdertest
      description: "First DBT Testing Purchase Order"

    - name: V_PURCHASE_ORDERITEM
      description: "vIEW WITH  Testing Purchase Order"